### ISSUE TITLE
Use Serde

### ISSUE THREAD

**Issue by ustulation** [maidsafe/rust_sodium#26]
We have moved to 1.16 and serde is now a reccommended and drop-in replacement for rustc-serialize for attribute deriviations of encodable and decodable. Rustc-serialize is going to be deprecated so we need to update to using serde (sodiumoxide is already using it).

**Comment by dtolnay** [comment]
Now rustc-serialize has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

**Comment by radupopescu** [comment]
Hi there!

I see that `rust_sodium` has an optional dependency on `serde = ~0.9.11`.

I'm not able to serialize the `Digest` struct in my code - the struct should automatically derive the `Serialize` trait. I can, however serialize my own struct which derives the trait. Is this because at lease `serde = 1.0.0` is needed for the `serde_derive` functionality?

Thanks!

**Comment by radupopescu** [comment]
I found the problem. I have to restrict the version of `serde` for my code to "^0.9.0". If my code picks up the 1.0 branch and `rust_sodium` sticks with 0.9, the code doesn't compile any longer.

**Comment by dbrgn** [comment]
This issue could probably be closed, since serde 1 is now [being used](https://github.com/maidsafe/rust_sodium/commit/b33592178a40bd1df50c956d21214d13fc8c7a5e#diff-80398c5faae3c069e4e6aa2ed11b28c0).

**Comment by ruuda** [comment]
Would be nice if the dependency were optional, behind a (default-on perhaps) feature, for people who do not need Serde.
